/* 
    lightbox / overlay
    references images on webpages generated by insert_image.js

    simple lightbox
    click on an image to see a caption and/or description
    An simple overlay appear when an image is clicked
    Images and descriptions are selected from class which the insert_image.js
    file created and applied to the html documents
*/

// selecting elements
const theLightbox = document.querySelector(".lightbox"); // lightbox on both pages
const captions = document.getElementsByClassName("caption"); // array of the corresponding captions
const slides = document.getElementsByClassName("slides"); // array of images with the slides class

// open and close the lightbox, works without specific ids and on both webpages
function openBox() {theLightbox.style.display = 'block';}
function closeBox() {
    theLightbox.style.display = 'none';

    for (i = 0; slides.length; i++) {
        slides[i].style.display = 'none';
        captions[i].style.display = 'none';
        // ensures all slides and caption are no longer visible
    }
}

function currentSlide(n) {
    // n is sent from the clicked image
    slides[n].style.display = 'block';
    captions[n].style.display = 'block';
};